<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        <h1>Welcome, ${name}</h1>
        <div>We are glad to see you on our website</div>
        <div>Please, click the link below to confirm your account</div>
        <a href ="http://localhost/confirm/${text}">confirm</a>
</body>
</html>